version: '3.0'
services:
  mytb:
    restart: unless-stopped
    image: "thingsboard/tb-postgres"
    ports:
      - "${TB_HTTP_PORT}:9090"
      - "${TB_MQTT_PORT}:1883"
      - "${TB_EDGE_RPC_PORT}:7070"
      - "${TB_COAP_LwM2M_PORTS}:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - mytb-data:/data
      - mytb-logs:/var/log/thingsboard

volumes:
  mytb-data:
    driver: local
  mytb-logs:
    driver: local
